@Clinic_Api_Host = https://localhost:7281

### Login
POST {{Clinic_Api_Host}}/api/user/login
Content-Type: application/json
{
  "Username": "nima",
  "password": "123456"
}

### Get All (requires JWT)
GET {{Clinic_Api_Host}}/api/user/getAllUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU1MDA3NjQzLCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.tnOvt8qWS1Mq4mUQZ7u53JrTJeEzFL1qHKHCvfe9DCI

### Get By ID
GET {{Clinic_Api_Host}}/api/user/getUserById/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU0NzUzNzIxLCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.mE3Dgii81P3hn9_wcWbmo7v4pYU3n6z2MKMr4h5eW5o

### Delete Usser
Delete {{Clinic_Api_Host}}/api/user/deleteUser/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU0NzUzNzIxLCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.mE3Dgii81P3hn9_wcWbmo7v4pYU3n6z2MKMr4h5eW5o

### Assign Role to User
PUT {{Clinic_Api_Host}}/api/user/assign-role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU0NzUzNzIxLCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.mE3Dgii81P3hn9_wcWbmo7v4pYU3n6z2MKMr4h5eW5o

{
  "userId": 1,
  "roleId": 2
}

### Create User (Admin only, requires JWT)
POST {{Clinic_Api_Host}}/api/user/createUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc0MjE1MDMsImlhdCI6MTc1NjgxNjcwMywidXNlcklkIjoiMiIsInVzZXJuYW1lIjoibmltYSIsInVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3NTY4MTY3MDN9.sk81ZXdOnVOyuSwtFrgc-gmHE0JPVd7PtdJwVw2pPhc

{
  "Username": "doctor",
  "password": "1234567",
  "firstName": "New",
  "lastName": "Doctor",
  "roleId": 9,
  "isActive": true
}

### Update User (Admin only, requires JWT)
PUT {{Clinic_Api_Host}}/api/user/updateUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU0NzUzNzIxLCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.mE3Dgii81P3hn9_wcWbmo7v4pYU3n6z2MKMr4h5eW5o

{
  "id": 3,
  "Username": "parhamversionpiercing",
  "firstName": "UpdatedFirstName",
  "lastName": "UpdatedLastName",
  "roleId": 1,
  "isActive": true
}

### Create Appointment
POST {{Clinic_Api_Host}}/api/treatment/createAppointment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjE1NzAwMjUsImlhdCI6MTc2MDk2NTIyNSwidXNlcklkIjoiMiIsInVzZXJuYW1lIjoibmltYSIsInVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3NjA5NjUyMjV9.HuMiNQYHgiChPcEZegH14f6AuMf-WKbT9lm91_EPAQ4

{
  "businessId": 2,
  "practitionerId": 4,
  "patientId": 6,
  "appointmentTypeId": 1,
  "start": "2025-08-18T10:00:00",
  "end": "2025-08-20T11:00:00",
  "repeatId": null,
  "repeatEvery": null,
  "endsAfter": null,
  "note": "salaaaaaaaaaaaam",
  "arrived": 0,
  "waitListId": null,
  "cancelled": false,
  "appointmentCancelTypeId": null,
  "cancelNotes": null,
  "isUnavailbleBlock": false,
  "lastUpdated": null,
  "isAllDay": false,
  "sendReminder": true,
  "appointmentSMS": null,
  "ignoreDidNotCome": false,
  "byInvoice": false,
  "editOrNew": 20
}

### Forgot Password
POST {{Clinic_Api_Host}}/api/user/forgotPassword
Content-Type: application/json

{
  "username": "john.doe",
  "newPassword": "MyNewSecurePass123"
}

### Get appointments with date
POST {{Clinic_Api_Host}}/api/treatment/getAppointments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU1NDI5OTMwLCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.f4r_G_wCuE1JQi-ZV1T0c0ZrGRQATltfv2laPiZDOjU
{
  "clinicId": 1,
  "Date": "2025-08-25",
  "doctorId": null
}

### Create a new patient
POST {{Clinic_Api_Host}}/api/patient/savePatient
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTg0NDExNzEsImlhdCI6MTc1NzgzNjM3MSwidXNlcklkIjoiMiIsInVzZXJuYW1lIjoibmltYSIsInVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3NTc4MzYzNzF9.cwqL8VDBlDE5Q6vrDosRtSm0-zdAowbGmenaE-m4SVY

{
  "titleId": 1,
  "firstName": "Nima2234",
  "lastName": "Ghahremanian",
  "gender": 1,
  "fatherName": "Ali",
  "birthDate": "1995-08-16",
  "email": "nima@example.com",
  "address1": "Street 123",
  "address2": "Apt 4B",
  "address3": "District 7",
  "city": "Tehran",
  "state": "Tehran",
  "postCode": "1234567890",
  "countryId": 276,
  "reminderTypeId": 2,
  "unsubscribeFromSMSMarketing": false,
  "receiveBookingConfirmationEmails": true,
  "invoiceTo": "Nima Ghahremanian",
  "emailInvoiceTo": "billing@example.com",
  "invoiceExtraInformation": "Paid by insurance",
  "emergencyContact": "09121234567",
  "referenceNumber": "REF-001",
  "referringDoctorId": 2,
  "notes": "Patient has no allergies",
  "referringInsurerId": 3,
  "referringInsurer2Id": null,
  "referringContactId": 7,
  "referringContact2Id": null,
  "referringPatientId": null,
  "patientCode": 101,
  "nationalCode": "1234567890",
  "jobId": 4,
  "referringInpatientInsurerId": null,
  "balance": 500000.00,
  "outBalance": 200000.00,
  "inBalance": 300000.00,
  "paperless": true,
  "editOrNew": -1
}

### Get Patients
GET {{Clinic_Api_Host}}/api/patient/getPatients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTg0NDExNzEsImlhdCI6MTc1NzgzNjM3MSwidXNlcklkIjoiMiIsInVzZXJuYW1lIjoibmltYSIsInVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3NTc4MzYzNzF9.cwqL8VDBlDE5Q6vrDosRtSm0-zdAowbGmenaE-m4SVY

### Get Treatments
GET {{Clinic_Api_Host}}/api/treatment/getTreatments/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU1NTM0MjE2LCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.m2aC3StvAxkQ8MWLhJDmDW0vkMv3i6rK0qxQXJH6k5A

### Get Sections
GET {{Clinic_Api_Host}}/api/main/getSections
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU1NTM0MjE2LCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.m2aC3StvAxkQ8MWLhJDmDW0vkMv3i6rK0qxQXJH6k5A

### Get Questions 
GET {{Clinic_Api_Host}}/api/question/getQuestions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU1NTM0MjE2LCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.m2aC3StvAxkQ8MWLhJDmDW0vkMv3i6rK0qxQXJH6k5A

### Save or Update QuestionValue
POST {{Clinic_Api_Host}}/api/Question/saveQuestionValue
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjA3ODY4MzEsImlhdCI6MTc2MDE4MjAzMSwidXNlcklkIjoiMiIsInVzZXJuYW1lIjoibmltYSIsInVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3NjAxODIwMzF9.PZk551c_2wz7du9ihwKJg33DI6F3BbTzL-h0H2E9XVg
{
  "questionId": 4,
  "selectedValue": "Yes",
  "invoiceItemId": 10,
  "answerId": 2
}

### Get Today Appointments
POST {{Clinic_Api_Host}}/api/treatment/getTodayAppointments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjE2NTg3NzUsImlhdCI6MTc2MTA1Mzk3NSwidXNlcklkIjoiMiIsInVzZXJuYW1lIjoibmltYSIsInVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3NjEwNTM5NzV9.RisBksPpDw5Iyx0CaZG1bRk1WXhVRhgJrCrVEcYxWBI
Content-Type: application/json

{
  "fromDate": "2025-10-12",  
  "toDate": "2025-10-12",         
  "clinic": null,                  
  "service": null,            
  "from": null,                       
  "to": null     
}

### Save Patient Phones
POST {{Clinic_Api_Host}}/api/patient/savePatientPhone
Authorization: Bearer 
Content-Type: application/json

{
  "patientId": 1,
  "phoneNoTypeId": 1,
  "number": "09129561523",
}

### Get Patient Phone
GET {{Clinic_Api_Host}}/api/patient/getPatientPhone/1
Authorization: Bearer
Content-Type: application/json

### Save Payments
POST {{Clinic_Api_Host}}/api/payment/savePayment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU2NjUyMjE4LCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.MVn8XLhTQglJ3ysHtn5YrIrZ7DEoFZ4Eh93JbgAE-cQ
Content-Type: application/json
{
  "paymentNo": null,
  "patientId": 2,
  "cash": null,
  "eFTPos": null,
  "other": null,
  "notes": null,
  "allowEdit": true,
  "paymentTypeId": 1,
  "editOrNew": -1
}

### Get All Payments
GET {{Clinic_Api_Host}}/api/payment/getAllPayments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU2NjUyMjE4LCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.MVn8XLhTQglJ3ysHtn5YrIrZ7DEoFZ4Eh93JbgAE-cQ
Content-Type: application/json

### Get Payment
GET {{Clinic_Api_Host}}/api/payment/getPayment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU2NjUyMjE4LCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.MVn8XLhTQglJ3ysHtn5YrIrZ7DEoFZ4Eh93JbgAE-cQ
Content-Type: application/json

### Delete Payment
GET {{Clinic_Api_Host}}/api/payment/deletePayment/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU2NjUyMjE4LCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.MVn8XLhTQglJ3ysHtn5YrIrZ7DEoFZ4Eh93JbgAE-cQ
Content-Type: application/json

### Get Clinics
GET {{Clinic_Api_Host}}/api/main/getClinics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU2ODA1NjE4LCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.S8z4iLf7sKv6IOaJNX2CVFGjM3IZaG5yK84Sv-VYTd8
Content-Type: application/json

### Get Countries
GET {{Clinic_Api_Host}}/api/contact/getCountries
Authorization: Bearer
Content-Type: application/json

### Get Week Appointments
GET {{Clinic_Api_Host}}/api/treatment/getWeeklyAppointments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTg3MTgzMjksImlhdCI6MTc1ODExMzUyOSwidXNlcklkIjoiMiIsInVzZXJuYW1lIjoibmltYSIsInVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3NTgxMTM1Mjl9.AMFg58a7xg8wMW0XzHYGvbSTlRj29g_KYVXXuU1d9I0
Content-Type: application/json

### Save BillableItems
POST {{Clinic_Api_Host}}/api/treatment/saveBillableItem
Authorization: Bearer
Content-Type: application/json
{
  "code": null,
  "name": "salam",
  "price": 10,
  "isOther": true,
  "itemTypeId": 1,
  "duration": 1,
  "allowEditPrice": true,
  "treatmentTemplateId": null,
  "forceOneInvoice": true,
  "isTreatmentDataRequired": true,
  "group": null,
  "parentId": null,
  "itemCategoryId": null,
  "orderInItemCategory": null,
  "autoCopyTreatment": true,
  "discountPercent": null,
  "needAccept": true,
  "lastTimeColor": null,
  "editOrNew": -1
}

### Delete BillableItem
GET {{Clinic_Api_Host}}/api/treatment/deleteBillableItem/1
Authorization: Bearer
Content-Type: application/json

### Get Patient ById
GET {{Clinic_Api_Host}}/api/patient/getPatientById/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTg2Mjc0MDUsImlhdCI6MTc1ODAyMjYwNSwidXNlcklkIjoiMiIsInVzZXJuYW1lIjoibmltYSIsInVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3NTgwMjI2MDV9.Bn_rBQnDX91i78gu4NdJPaL5PWHqnh-dMhZnvzJss1U
Content-Type: application/json

### Get Patient Invoices
GET {{Clinic_Api_Host}}/api/patient/getPatientInvoices/1
Authorization: Bearer
Content-Type: application/json

### Get Patient Receipts
GET {{Clinic_Api_Host}}/api/patient/getPatientReceipts/34
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjA1MTU2MTIsImlhdCI6MTc1OTkxMDgxMiwidXNlcklkIjoiMiIsInVzZXJuYW1lIjoibmltYSIsInVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3NTk5MTA4MTJ9.xu6WOOL6m9f4wldEiAMBxy40_EB_auY4VESE9180Ug8
Content-Type: application/json

### Get Patient Payments
GET {{Clinic_Api_Host}}/api/patient/getPatientPayments/2
Authorization: Bearer
Content-Type: application/json

### Save Product
POST {{Clinic_Api_Host}}/api/main/saveProduct
Authorization: Bearer
Content-Type: application/json
{
  "code": null,
  "name": null,
  "serialNumber": null,
  "supplier": null,
  "price": 100,
  "stockLevel": null,
  "notes": null,
  "isActive": true,
  "editOrNew": -1
}

### Get Products
GET {{Clinic_Api_Host}}/api/main/getProducts
Authorization: Bearer
Content-Type: application/json

### Delete Product
GET {{Clinic_Api_Host}}/api/main/deleteProduct/1
Authorization: Bearer
Content-Type: application/json

### Get Section Per Service
GET {{Clinic_Api_Host}}/api/treatment/getSectionPerService/1
Authorization: Bearer
Content-Type: application/json

### Get Question Per Section
GET {{Clinic_Api_Host}}/api/treatment/getQuestionsPerSection/1
Authorization: Bearer
Content-Type: application/json

### Get Answers Per Question
GET {{Clinic_Api_Host}}/api/treatment/getAnswersPerQuestion/1
Authorization: Bearer
Content-Type: application/json

### Get Patient Services 
GET {{Clinic_Api_Host}}/api/treatment/getPatientServices/1
Authorization: Bearer
Content-Type: application/json

### Save Attachment
POST {{Clinic_Api_Host}}/api/patient/saveAttachment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjEzODY5ODIsImlhdCI6MTc2MDc4MjE4MiwidXNlcklkIjoiMiIsInVzZXJuYW1lIjoibmltYSIsInVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3NjA3ODIxODJ9.MEURmD3D6fvkxLULhm-SuAy_PhCc_8kdZv2vMqUc1Q8
Content-Type: application/json
{
  "patientId": 1,
  "filename": "test.png",
  "base64": "",
  "editOrNew": -1,
  "invoiceItemId": 10281424
}

### Get Attachment
Get {{Clinic_Api_Host}}/api/patient/getAttachment/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjEzODY5ODIsImlhdCI6MTc2MDc4MjE4MiwidXNlcklkIjoiMiIsInVzZXJuYW1lIjoibmltYSIsInVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3NjA3ODIxODJ9.MEURmD3D6fvkxLULhm-SuAy_PhCc_8kdZv2vMqUc1Q8
Content-Type: application/json

### Get Patient Treatments 
GET {{Clinic_Api_Host}}/api/treatment/getPatientTreatments/677613
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjA5NDczMzQsImlhdCI6MTc2MDM0MjUzNCwidXNlcklkIjoiMiIsInVzZXJuYW1lIjoibmltYSIsInVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3NjAzNDI1MzR9.bEgZQkG1AOhPp5DjJaQx9jnkbbxKKEskSgEWZzC1gcs
Content-Type: application/json

### Save or Update InvoiceItem
POST {{Clinic_Api_Host}}/api/Invoice/SaveInvoiceItem
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjA3ODY4MzEsImlhdCI6MTc2MDE4MjAzMSwidXNlcklkIjoiMiIsInVzZXJuYW1lIjoibmltYSIsInVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3NjAxODIwMzF9.PZk551c_2wz7du9ihwKJg33DI6F3BbTzL-h0H2E9XVg

{
  "invoiceId": 1012408,
  "itemId": 9058947,
  "productId": 3,
  "quantity": 2,
  "discount": 10,
  "discountTypeId": 1,
  "editOrNew": -1
}

### GetInvoices By Clinic
Post {{Clinic_Api_Host}}/api/report/getInvoicesByClinic
Content-Type: application/json
Authorization: Bearer
{
  "fromDate": "2025-08-18T00:00:00",
  "toDate": "2025-08-18T00:00:00"
}

### GetInvoicesByService
POST {{Clinic_Api_Host}}/api/report/getInvoicesByService
Content-Type: application/json
Authorization: Bearer
{
  "fromDate": "2025-08-18T00:00:00",
  "toDate": "2025-08-18T00:00:00"
}

### GetAppointmentsAndUnpaidInvoices
POST {{Clinic_Api_Host}}/api/report/getAppointmentsAndUnpaidInvoices
Content-Type: application/json
Authorization: Bearer
{
   "fromDate": "2025-08-18T00:00:00",
  "toDate": "2025-08-18T00:00:00"
}